project_name = "petabytepeddler"
region = "us-central1"
region_zone_a = "us-central1-a"
region_zone_b = "us-central1-b"
machine_type = "n1-standard-2" // Min req for ES
network_tags = ["total-news-elasticsearch", "http-server", "https-server"]
ports_to_open = ["9000", "5601", "80","9200","443","9300","3000"] // for loadbalancer
machine_access_scopes = ["cloud-platform","userinfo-email", "compute-ro", "storage-rw", "monitoring-write", "logging-write", "https://www.googleapis.com/auth/trace.append"]
node_ips = ["10.128.0.2", "10.128.0.3", "10.128.0.4"]  // IPs within my subnet
gce_image = "debian-cloud/debian-10"
ssh_tags = ["ssh-kibana","ssh-elastics"]
internal_kafka_ip = "10.128.0.33" // IP address (within the subnet) to your internal load balanceer