variable "project_name" {}
variable "region" {}
variable "region_zone_a" {} 
variable "region_zone_b" {} 
variable "machine_type" {}  
variable "network_tags" {} 
variable "ports_to_open" {}
variable "machine_access_scopes" {} 
variable "node_ips" {} 
variable "gce_image" {} 
variable "ssh_tags" {} 
variable "internal_kafka_ip" {}