variable "project_name" {}
variable "region" {}
variable "region_zone_a" {} 
variable "region_zone_b" {} 
variable "machine_type" {} 
variable "machine_type_medium" {} 
variable "network_tags" {} 
variable "kibana_tags" {}
variable "ports_to_open" {}
variable "machine_access_scopes" {} 
variable "node_ips" {} 
variable "master_node" {} 
variable "gce_image" {} 
variable "es_webapp_image" {}
variable "ssh_tags" {} 
variable "ca_bucket_location" {} 
variable "backup_bucket" {} 
variable "internal_lb_ip" {}