version: '3.7'
services:
  client:
    image: mhart/alpine-node:16.0
    restart: always
    ports:
      - "3000:3000"
    working_dir: /client/src/app
    volumes:
      - ./client:/client/src/app
    entrypoint: ["npm", "start"]
    links:
      - server
    networks:
      - elastic-app-network
            
  server:
    image: mhart/alpine-node:16.0
    restart: always
    ports:
      - "3050:3050"
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - elastic-app-network

networks:
  elastic-app-network:
    driver: bridge